import { refreshLedger } from '../games/arcadeRewards.js';
import { TurnstileWidget } from './TurnstileWidget.js';
const css=(e,o)=>Object.assign(e.style,o);const mk=(t,p,x='')=>{const e=document.createElement(t);e.textContent=x;p?.appendChild(e);return e};
const BTN={minHeight:'38px',padding:'0 12px',borderRadius:'9px',border:'1px solid #86e05a',background:'#193014',color:'#d6ffc2',font:'800 11px system-ui',cursor:'pointer'};
const token=()=>{try{return sessionStorage.getItem('veyra:api-session')}catch{return null}};
const FRIENDLY={TURNSTILE_REQUIRED:'Complete the security check before requesting a withdrawal.',TURNSTILE_FAILED:'Security verification failed or expired. Please try again.',TURNSTILE_UNAVAILABLE:'Security verification is temporarily unavailable. Please try again shortly.'};
async function request(path,opts={}){const r=await fetch(path,{cache:'no-store',...opts,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()||''}`,...(opts.headers||{})}}),d=await r.json();if(!r.ok)throw new Error(FRIENDLY[d.error]||d.error||'Request failed');return d;}
const fmt=v=>Number(v||0).toFixed(8).replace(/0+$/,'').replace(/\.$/,'');
export class ArcadeBalancePanel{
 constructor(game){this.game=game;this.open=false;this.turnstile=null;this._build();}
 _build(){const root=mk('div');css(root,{position:'fixed',inset:'0',display:'none',alignItems:'center',justifyContent:'center',zIndex:'68',background:'rgba(4,7,4,.72)'});const panel=mk('section',root);css(panel,{width:'min(96vw,760px)',maxHeight:'90vh',overflow:'auto',padding:'12px',borderRadius:'16px',border:'2px solid #86e05a',background:'linear-gradient(180deg,#141d11,#090e08)',color:'#eef8e9',boxSizing:'border-box'});const head=mk('div',panel);css(head,{display:'flex',alignItems:'center',gap:'8px'});const back=mk('button',head,'← BACK');css(back,BTN);back.onclick=()=>this.close();const title=mk('h2',head,'ARCADE ACCOUNT');css(title,{flex:1,textAlign:'center',font:'900 17px system-ui',letterSpacing:'2px'});this.status=mk('div',panel);css(this.status,{padding:'8px',textAlign:'center',color:'#b8f0a0',font:'800 11px system-ui'});this.body=mk('div',panel);css(this.body,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:'10px'});root.onclick=e=>{if(e.target===root)this.close()};document.body.appendChild(root);this.root=root;}
 card(title){const c=mk('section',this.body);css(c,{padding:'10px',borderRadius:'11px',background:'rgba(0,0,0,.28)',border:'1px solid rgba(134,224,90,.28)'});const h=mk('h3',c,title);css(h,{margin:'0 0 8px',color:'#d6ffc2',font:'900 12px system-ui',letterSpacing:'1px'});return c;}
 async _render(){this.turnstile?.dispose();this.turnstile=null;this.body.innerHTML='';if(!token()){this.status.textContent='Connect and authenticate your wallet from Game Main.';return;}this.status.textContent='Loading authoritative account data…';try{const [wd,sv]=await Promise.all([request('/api/withdrawals'),request('/api/social-verification')]);this.status.textContent=`Balance ${fmt(wd.account.balance)} zkLTC · Available ${fmt(wd.account.available)} · Reserved ${fmt(wd.account.reserved)}`;this._withdrawal(wd);this._verification(sv,wd.account.verificationStatus);}catch(e){this.status.textContent=e.message;}}
 _withdrawal(d){const c=this.card('ARCADE WITHDRAWAL');const info=mk('p',c,`Minimum 0.005 zkLTC · Destination ${d.account.wallet}`);css(info,{font:'700 10px system-ui',overflowWrap:'anywhere',color:'#aebda8'});const input=mk('input',c);input.placeholder='0.005';input.inputMode='decimal';css(input,{width:'100%',height:'38px',boxSizing:'border-box',borderRadius:'8px',background:'#090d08',color:'#fff',border:'1px solid #587446',padding:'0 9px'});
  const eligible=d.account.verificationStatus==='not_required'&&Number(d.account.available)>=.005,challenge=mk('div',c);challenge.className='arcade-turnstile';css(challenge,{display:eligible?'block':'none',minHeight:'66px',marginTop:'7px',padding:'5px',borderRadius:'9px',border:'1px solid rgba(122,107,178,.42)',background:'rgba(8,0,32,.3)',overflow:'hidden'});const challengeState=mk('div',c,eligible?'Loading security check…':'');css(challengeState,{display:eligible?'block':'none',minHeight:'16px',marginTop:'3px',color:'#c9c0dd',font:'600 9px system-ui',textAlign:'center'});
  const btn=mk('button',c,'REQUEST WITHDRAWAL');css(btn,{...BTN,width:'100%',marginTop:'6px'});let turnstileReady=false,submitting=false;btn.disabled=true;
  if(eligible){this.turnstile=new TurnstileWidget(challenge,{action:'arcade_withdrawal',onState:({state,message})=>{turnstileReady=state==='verified';challengeState.textContent=state==='verified'?'Security check complete.':message||'Complete the security check.';btn.disabled=submitting||!turnstileReady;}});this.turnstile.mount();}
  btn.onclick=async()=>{if(submitting)return;const turnstileToken=this.turnstile?.consume();if(!turnstileToken){this.status.textContent='Complete the security check before requesting a withdrawal.';this.turnstile?.reset();return;}submitting=true;turnstileReady=false;btn.disabled=true;btn.textContent='VERIFYING & SUBMITTING…';try{await request('/api/withdrawals',{method:'POST',body:JSON.stringify({amount:input.value,idempotencyKey:crypto.randomUUID(),turnstileToken})});await refreshLedger();await this._render();}catch(e){this.status.textContent=e.message;submitting=false;btn.textContent='REQUEST WITHDRAWAL';this.turnstile?.reset();btn.disabled=true;}};
  const h=mk('div',c);css(h,{marginTop:'9px',display:'grid',gap:'5px'});for(const w of d.withdrawals){const row=mk('div',h);css(row,{padding:'7px',borderRadius:'7px',background:'#10180e',font:'700 10px system-ui'});row.textContent=`${fmt(w.amount)} zkLTC · ${String(w.status).toUpperCase()} · ${new Date(w.requested_at).toLocaleString()} · ${w.payment_reference||w.transaction_hash||w.wallet}`;}}
 _verification(d,status){if(status==='not_required')return;const c=this.card('FIRST WITHDRAWAL VERIFICATION');mk('p',c,status==='pending'?'Verification pending admin review.':status==='rejected'?'Rejected — submit improved proof below.':'Follow both accounts and submit screenshot proof.');for(const [label,url] of [['FOLLOW VEYRA WORLD FOUNDER','https://x.com/HeisHim94'],['FOLLOW OFFICIAL VEYRA GAME','https://x.com/VEYRAWLD']]){const a=mk('a',c,label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';css(a,{...BTN,display:'flex',alignItems:'center',justifyContent:'center',margin:'5px 0',textDecoration:'none'});}if(status==='pending')return;const user=mk('input',c);user.placeholder='X username';const file=mk('input',c);file.type='file';file.accept='image/png,image/jpeg,image/webp';for(const x of [user,file])css(x,{width:'100%',margin:'4px 0',boxSizing:'border-box'});const submit=mk('button',c,'SUBMIT VERIFICATION');css(submit,{...BTN,width:'100%'});submit.onclick=()=>{const f=file.files?.[0];if(!f)return this.status.textContent='Choose a screenshot.';if(f.size>800000)return this.status.textContent='Screenshot must be under 800 KB.';const reader=new FileReader();reader.onload=async()=>{submit.disabled=true;try{await request('/api/social-verification',{method:'POST',body:JSON.stringify({xUsername:user.value,screenshotData:reader.result})});await this._render();}catch(e){this.status.textContent=e.message;submit.disabled=false;}};reader.readAsDataURL(f);};}

 toggle(){this.open?this.close():this.show()}show(){if(this.open)return;this.open=true;this.root.style.display='flex';this._render();this.game.audio.play('click')}close(){if(!this.open)return;this.open=false;this.turnstile?.dispose();this.turnstile=null;this.root.style.display='none';this.game.audio.play('back')}
}
