// Always-visible city minimap. Playable geometry is projected directly from
// cityMap.js; no look-alike copy of the developed world is maintained here.
import {CITY_ATLAS,worldToAtlas} from '../world/cityAtlas.js';
import {GROUND_RECTS,ROADS,BUILDINGS,PARK_PATHS,POND,POOL,STREAMS} from '../world/cityMap.js';
const COLORS={grass:'#70925c',plaza:'#b69f76',sidewalk:'#b4aa94',pavement:'#989287',gravel:'#9a876b',parking:'#50545a',rockpad:'#716c65'};
export class CityMinimap{
 constructor(game){this.game=game;this.visible=false;this._build();}
 _build(){const wrap=document.createElement('aside');wrap.id='city-minimap';wrap.setAttribute('aria-label','Live Veyra city minimap');Object.assign(wrap.style,{position:'fixed',left:'max(10px,env(safe-area-inset-left))',top:'max(58px,calc(env(safe-area-inset-top) + 48px))',zIndex:'24',display:'none',width:'184px',aspectRatio:'1.38',border:'1.5px solid rgba(231,204,132,.82)',borderRadius:'14px',overflow:'hidden',background:'rgba(10,17,23,.9)',boxShadow:'0 8px 28px #0009,inset 0 0 20px #0006',pointerEvents:'none',backdropFilter:'blur(4px)'});const title=document.createElement('div');title.textContent='VEYRA CITY';Object.assign(title.style,{position:'absolute',zIndex:'2',left:'8px',top:'6px',padding:'3px 6px',borderRadius:'6px',background:'#111923cc',color:'#f5e2ad',font:'900 9px Trebuchet MS,system-ui',letterSpacing:'1.2px'});wrap.appendChild(title);const north=document.createElement('div');north.innerHTML='<b>N</b><i></i>';Object.assign(north.style,{position:'absolute',zIndex:'2',right:'8px',top:'6px',color:'#fff4d2',font:'900 10px Georgia',textAlign:'center',textShadow:'0 1px 3px #000'});const arrow=north.querySelector('i');Object.assign(arrow.style,{display:'block',margin:'1px auto',width:'0',height:'0',borderLeft:'4px solid transparent',borderRight:'4px solid transparent',borderBottom:'7px solid #e6c66e'});wrap.appendChild(north);this.canvas=document.createElement('canvas');Object.assign(this.canvas.style,{width:'100%',height:'100%',display:'block'});wrap.appendChild(this.canvas);document.body.appendChild(wrap);this.root=wrap;this.ctx=this.canvas.getContext('2d');window.addEventListener('resize',()=>this._resize());}
 show(){if(this.visible)return;this.visible=true;this.cam=null;this.root.style.display='block';this.root.style.visibility='visible';this._resize();this._tick();}
 hide(){this.visible=false;this.root.style.display='none';}
 setPausedHidden(hidden){this.root.style.visibility=hidden?'hidden':'visible';}
 _resize(){if(!this.visible)return;const mobile=innerWidth<900||matchMedia?.('(pointer: coarse)').matches;this.root.style.width=(mobile?'138px':'184px');const r=this.root.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(r.width*d));this.canvas.height=Math.max(1,Math.round(r.height*d));this.dpr=d;}
 _tick(){if(!this.visible)return;this.draw(performance.now()/1000);requestAnimationFrame(()=>this._tick());}
 _rect(c,r,ox,oy,s){c.fillRect(ox+r.x*s,oy+r.y*s,r.w*s,r.h*s);}
 draw(time){const c=this.ctx,d=this.dpr||1,W=this.canvas.width/d,H=this.canvas.height/d,pad=7,model=this.game.states.get('play')?.model,p=model?.player,playerAtlas=p?worldToAtlas(p.x,p.y):{x:CITY_ATLAS.width/2,y:CITY_ATLAS.height/2},s=Math.min((W-pad*2)/CITY_ATLAS.width,(H-pad*2)/CITY_ATLAS.height)*1.38,halfW=(W-pad*2)/(2*s),halfH=(H-pad*2)/(2*s);if(!this.cam)this.cam={...playerAtlas};this.cam.x+=(playerAtlas.x-this.cam.x)*.09;this.cam.y+=(playerAtlas.y-this.cam.y)*.09;this.cam.x=Math.max(halfW,Math.min(CITY_ATLAS.width-halfW,this.cam.x));this.cam.y=Math.max(halfH,Math.min(CITY_ATLAS.height-halfH,this.cam.y));const ox=W/2-this.cam.x*s,oy=H/2-this.cam.y*s;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,W,H);c.fillStyle='#15252c';c.fillRect(0,0,W,H);
  // Master coordinate-layout: every future area is still a real atlas region.
  for(const q of CITY_ATLAS.districts){c.globalAlpha=q.status==='future'?.56:.82;c.fillStyle=q.color;c.fillRect(ox+q.x*s,oy+q.y*s,q.w*s,q.h*s);c.strokeStyle=q.status==='future'?'#ead8aa55':'#f4e2b288';c.lineWidth=.8;c.strokeRect(ox+q.x*s,oy+q.y*s,q.w*s,q.h*s);}c.globalAlpha=1;
  c.lineCap='round';for(const road of CITY_ATLAS.roads){c.strokeStyle=road.kind==='promenade'?'#d9bd79':'#42484d';c.lineWidth=Math.max(1.5,(road.kind==='avenue'?82:46)*s);c.beginPath();road.points.forEach((p,i)=>i?c.lineTo(ox+p[0]*s,oy+p[1]*s):c.moveTo(ox+p[0]*s,oy+p[1]*s));c.stroke();}
  // Exact current-world geometry transformed through the canonical mount.
  const mount=CITY_ATLAS.playableAreas[0],px=ox+mount.atlasX*s,py=oy+mount.atlasY*s;
  for(const r of GROUND_RECTS){c.fillStyle=COLORS[r.t]||'#918a7d';this._rect(c,r,px,py,s);}for(const r of PARK_PATHS){c.fillStyle=COLORS.gravel;this._rect(c,r,px,py,s);}for(const r of ROADS){c.fillStyle='#42474d';this._rect(c,r,px,py,s);}
  c.fillStyle='#5395a5';c.beginPath();c.ellipse(px+POND.x*s,py+POND.y*s,POND.rx*s,POND.ry*s,0,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(px+POOL.x*s,py+POOL.y*s,POOL.rx*s,POOL.ry*s,0,0,Math.PI*2);c.fill();for(const r of STREAMS)this._rect(c,r,px,py,s);
  for(const b of BUILDINGS){const fy=b.frontY??700;c.fillStyle=b.venue?'#5f426f':'#3d5360';c.fillRect(px+(b.cx-b.w/2)*s,py+(fy-420)*s,b.w*s,420*s);c.strokeStyle='#e1cf9b';c.lineWidth=.6;c.strokeRect(px+(b.cx-b.w/2)*s,py+(fy-420)*s,b.w*s,420*s);}
  // Landmarks use atlas coordinates; the Litecoin monument gets a live glow.
  for(const l of CITY_ATLAS.landmarks){const x=ox+l.x*s,y=oy+l.y*s;if(l.id==='statue'||l.id==='bitcoin-monument'){const rr=5+Math.sin(time*2)*.8;c.fillStyle='#ffd76c38';c.beginPath();c.arc(x,y,rr+3,0,Math.PI*2);c.fill();c.fillStyle='#e5c468';c.beginPath();c.arc(x,y,rr,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.font='900 8px Trebuchet MS';c.textAlign='center';c.textBaseline='middle';c.fillText(l.id==='bitcoin-monument'?'₿':'Ł',x,y+.5);}else{c.fillStyle=l.status==='playable'?'#f1d992':'#ded6bf99';c.beginPath();c.arc(x,y,l.status==='playable'?2.4:1.5,0,Math.PI*2);c.fill();}}
  if(p){const a=worldToAtlas(p.x,p.y),x=ox+a.x*s,y=oy+a.y*s,moving=Math.hypot(p.vx||0,p.vy||0)>.1,facingAngle={up:0,right:Math.PI/2,down:Math.PI,left:-Math.PI/2}[p.facing]||0,ang=moving?Math.atan2(p.vy,p.vx)+(Math.PI/2):facingAngle;c.save();c.translate(x,y);c.rotate(Number.isFinite(ang)?ang:0);c.shadowColor='#35e0ff';c.shadowBlur=6;c.fillStyle='#35e0ff';c.strokeStyle='#fff';c.lineWidth=1;c.beginPath();c.moveTo(0,-7);c.lineTo(5,5);c.lineTo(0,3);c.lineTo(-5,5);c.closePath();c.fill();c.stroke();c.restore();}
  c.strokeStyle='#f0d68d88';c.lineWidth=1;c.strokeRect(ox+.5,oy+.5,CITY_ATLAS.width*s-1,CITY_ATLAS.height*s-1);
 }
}
