const css=(e,o)=>Object.assign(e.style,o);const mk=(tag,parent,text)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(parent)parent.appendChild(e);return e};
const BTN={minHeight:'46px',padding:'0 16px',borderRadius:'10px',border:'1px solid #4ba6c8',background:'#18394b',color:'#d9f6ff',font:'800 13px system-ui',cursor:'pointer'};
const amount=(v,d=8)=>v==null?'—':`${Number(v).toFixed(d).replace(/0+$/,'').replace(/\.$/,'')} zkLTC`;
export class WalletPanel{
 constructor(game){this.game=game;this.open=false;this._build();game.events.on('litvm:wallet',s=>this.render(s));}
 _build(){const root=mk('div');css(root,{position:'fixed',inset:'0',display:'none',alignItems:'center',justifyContent:'center',zIndex:'70',background:'rgba(4,7,14,.7)'});const panel=mk('section',root);css(panel,{width:'min(94vw,480px)',padding:'16px',borderRadius:'18px',border:'2px solid #4ba6c8',background:'linear-gradient(180deg,#111b2b,#090e18)',boxShadow:'0 20px 70px #000b',color:'#eef8ff'});const head=mk('div',panel);css(head,{display:'flex',alignItems:'center',gap:'10px'});this.back=mk('button',head,'← BACK');css(this.back,BTN);const title=mk('div',head,'LITVM WALLET');css(title,{flex:'1',textAlign:'center',font:'900 18px system-ui',letterSpacing:'2px'});this.status=mk('div',panel);css(this.status,{margin:'13px 0',padding:'9px',borderRadius:'9px',background:'#090e17',color:'#87dfff',font:'800 12px system-ui',textAlign:'center'});this.address=this._row(panel,'CONNECTED WALLET','Not connected');this.main=this._row(panel,'MAIN WALLET BALANCE','—');this.arcade=this._row(panel,'ARCADE GAME BALANCE','0.00000 zkLTC');const note=mk('p',panel,'Main Wallet is the actual connected LitVM Testnet zkLTC balance used for casino wagers. Arcade Game Balance is Veyra’s internal server-validated reward balance and is not on-chain until a confirmed smart-contract withdrawal.');css(note,{color:'#aebbd0',font:'700 11.5px system-ui',lineHeight:'1.5'});const actions=mk('div',panel);css(actions,{display:'flex',gap:'8px',flexWrap:'wrap',justifyContent:'center'});this.refresh=mk('button',actions,'REFRESH BALANCES');this.disconnect=mk('button',actions,'DISCONNECT');for(const b of [this.refresh,this.disconnect])css(b,BTN);this.back.addEventListener('click',()=>this.hide());this.refresh.addEventListener('click',()=>this._refresh());this.disconnect.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();this.game.walletSession.disconnect();this.hide();});root.addEventListener('pointerdown',e=>{if(e.target===root)this.hide()});document.body.appendChild(root);this.root=root;this.render(this.game.walletSession.snapshot());}
 _row(parent,label,value){const row=mk('div',parent);css(row,{padding:'11px 12px',margin:'8px 0',border:'1px solid #25364d',borderRadius:'11px',background:'#0c1320'});const l=mk('div',row,label);css(l,{color:'#8799b5',font:'800 10px system-ui',letterSpacing:'1px'});const v=mk('div',row,value);css(v,{marginTop:'5px',font:'900 15px system-ui',wordBreak:'break-all'});return v;}
 async _refresh(){this.refresh.disabled=true;try{await this.game.walletSession.refresh();}catch{}this.refresh.disabled=false;}
 render(s){this.status.textContent=`${s.state.toUpperCase()}${s.detail?' · '+s.detail:''}`;this.status.dataset.state=s.state;this.status.style.color=s.state==='failed'?'#ff7b7b':s.state==='confirmed'?'#8bea69':s.state==='awaiting signature'||s.state==='confirming'||s.state==='submitted'?'#ffd477':'#87dfff';this.address.textContent=s.address||'Not connected';this.main.textContent=amount(s.mainBalance);this.arcade.textContent=amount(s.arcadeBalance,5);this.refresh.style.display=s.address?'block':'none';this.disconnect.style.display=s.address?'block':'none';}
 show(){this.open=true;this.wasLocked=this.game.input.locked;this.game.input.locked=true;this.root.style.display='flex';this.render(this.game.walletSession.snapshot());}
 hide(){this.open=false;this.root.style.display='none';if(!this.wasLocked&&!this.game.overlay.openId)this.game.input.locked=false;}
 toggle(){this.open?this.hide():this.show();}
}
