// Arcade timing basketball: stop the moving heat dot inside a randomized zone.
import { Storage } from '../core/Storage.js';
const HOOP={x:2140,y:1400,z:36},KEY='veyra:basketball-high-score';
const css=(e,o)=>Object.assign(e.style,o),mk=(tag,p,text='')=>{const e=document.createElement(tag);e.textContent=text;p.appendChild(e);return e};
export class BasketballGame{
 constructor(game){this.game=game;this.active=false;this.score=0;this.high=Number(Storage.get(KEY,0))||0;this.time=60;this.pos=.08;this.dir=1;this.target=.5;this.zoneW=.08;this.level=0;this.dotSpeed=1.15;this.ball=null;this.fx=[];this.status='STOP THE DOT IN THE GREEN ZONE';this._build();window.addEventListener('keydown',e=>this._key(e));window.addEventListener('pointerdown',e=>{if(this.active&&e.pointerType==='mouse'&&e.button===0&&!this.panel.contains(e.target))this.shootBall()});}
 _build(){const p=mk('section',document.body);p.setAttribute('aria-label','Basketball timing minigame');css(p,{position:'fixed',zIndex:'44',left:'50%',bottom:'max(12px,env(safe-area-inset-bottom))',transform:'translateX(-50%)',display:'none',alignItems:'center',gap:'10px',padding:'9px 12px',border:'1.5px solid #e7c56f',borderRadius:'15px',background:'linear-gradient(180deg,rgba(36,28,34,.96),rgba(13,19,25,.97))',boxShadow:'0 10px 35px #000a',color:'#fff7df',font:'800 12px Trebuchet MS,system-ui'});this.panel=p;this.stats=mk('div',p);css(this.stats,{minWidth:'112px',lineHeight:'1.45'});const middle=mk('div',p);css(middle,{display:'grid',gap:'5px',justifyItems:'center'});this.hint=mk('div',middle,'HEAT BAR');css(this.hint,{font:'900 10px Trebuchet MS',color:'#ffe29a',letterSpacing:'1.4px'});this.bar=mk('div',middle);css(this.bar,{position:'relative',width:'150px',height:'18px',borderRadius:'10px',background:'linear-gradient(90deg,#4f8fe8 0%,#55d7c4 28%,#f4d153 55%,#ed803f 78%,#da3f45 100%)',overflow:'hidden',border:'2px solid #ffffffaa',boxShadow:'inset 0 1px 5px #0008'});this.zone=mk('i',this.bar);css(this.zone,{position:'absolute',top:'0',height:'100%',background:'rgba(80,255,137,.5)',borderLeft:'2px solid #d7ffe2',borderRight:'2px solid #d7ffe2',boxShadow:'0 0 10px #62ff9a',transition:'left .2s ease,width .2s ease'});this.dot=mk('b',this.bar);css(this.dot,{position:'absolute',top:'50%',width:'12px',height:'12px',margin:'-6px 0 0 -6px',borderRadius:'50%',background:'#fff',border:'2px solid #222',boxShadow:'0 0 7px #fff',zIndex:'2'});this.shoot=mk('button',p,'SHOOT');css(this.shoot,{height:'54px',minWidth:'116px',padding:'0 18px',border:'2px solid #65e7fa',borderRadius:'14px',background:'linear-gradient(#39cce2,#176c81)',boxShadow:'0 4px 16px #21bcd666',color:'#fff',font:'900 18px Trebuchet MS',touchAction:'manipulation'});this.shoot.addEventListener('pointerdown',e=>{e.preventDefault();this.shootBall()});this.exit=mk('button',p,'EXIT');css(this.exit,{height:'44px',padding:'0 13px',border:'1px solid #cfb66e',borderRadius:'11px',background:'linear-gradient(#4a4044,#252833)',color:'#fff',font:'900 13px Trebuchet MS'});this.exit.onclick=()=>this.stop(false);}
 _newTarget(){this.target=.5;this.zoneW=.08;this.dotSpeed=Math.min(3.2,1.15+this.level*.22);this.zone.style.left='46%';this.zone.style.width='8%';this.pos=this.dir>0?.04:.96;this.dot.style.left=(this.pos*100)+'%';}
 start(player){if(this.active)return;this.active=true;this.player=player;this.score=0;this.time=60;this.level=0;this.dotSpeed=1.15;this.ball=null;this.fx=[];this.status='STOP THE DOT IN THE GREEN ZONE';this.dir=1;this._newTarget();player.vx=player.vy=0;player.facing='right';this.panel.style.display='flex';this.game.audio.play('confirm');this._stats();}
 stop(timeout=false){if(!this.active)return;this.active=false;this.ball=null;this.panel.style.display='none';if(this.score>this.high){this.high=this.score;Storage.set(KEY,this.high);}this.game.audio.play(this.score?'confirm':'back');this.game.events.emit('basketball:end',{score:this.score,highScore:this.high,timeout,noReward:true});}
 shootBall(){if(!this.active||this.ball)return;const distance=Math.abs(this.pos-.5),made=distance<=this.zoneW/2,quality=made?1-distance/(this.zoneW/2):0,spread=made?0:(this.pos<.5?-1:1)*(30+Math.random()*22),p=this.player;this.ball={sx:p.x+14,sy:p.y-8,x:p.x+14,y:p.y-8,z:18,tx:HOOP.x,ty:HOOP.y+spread,u:0,dur:.76-quality*.08,arc:84+quality*20,made,quality,phase:'fly',wait:0};this.status=made?'PERFECT!':'MISS!';this.shoot.disabled=true;this.game.audio.play('shot');this._stats();}
 _key(e){if(!this.active)return;if((e.code==='Space'||e.code==='Enter')&&!e.repeat){e.preventDefault();this.shootBall();}else if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();this.stop(false);}}
 update(dt){if(!this.active)return;this.time=Math.max(0,this.time-dt);if(this.time<=0){this.stop(true);return;}if(!this.ball){this.pos+=this.dir*dt*this.dotSpeed;if(this.pos>=1){this.pos=1;this.dir=-1;}else if(this.pos<=0){this.pos=0;this.dir=1;}this.dot.style.left=(this.pos*100)+'%';}const b=this.ball;if(b){if(b.phase==='fly'){b.u=Math.min(1,b.u+dt/b.dur);const e=1-Math.pow(1-b.u,2);b.x=b.sx+(b.tx-b.sx)*e;b.y=b.sy+(b.ty-b.sy)*e;b.z=18+(HOOP.z-18)*e+Math.sin(b.u*Math.PI)*b.arc;if(b.u>=1){if(b.made){this.score++;this.level++;if(this.score>this.high){this.high=this.score;Storage.set(KEY,this.high);}this.status='PERFECT! +1';this.game.audio.play('win');for(let i=0;i<16;i++)this.fx.push({x:HOOP.x,y:HOOP.y-7,vx:(Math.random()-.5)*100,vy:(Math.random()-.5)*80,life:.72,c:i%2?'#ffd25d':'#63e8ff'});}else{this.status='MISS!';this.game.audio.play('hit');}b.phase='drop';b.wait=0;this._stats();}}else{b.wait+=dt;b.z=Math.max(0,HOOP.z-b.wait*170);if(!b.made){b.x+=38*dt;b.y+=18*dt;b.z=Math.abs(Math.sin(b.wait*12))*Math.max(0,18-b.wait*22);}if(b.wait>.34){this.ball=null;this.shoot.disabled=false;this.status='CENTER ZONE — STOP THE DOT!';this.dir*=-1;this._newTarget();this._stats();}}}for(const q of this.fx){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=55*dt;q.life-=dt;}this.fx=this.fx.filter(q=>q.life>0);this._stats();}
 _stats(){this.stats.innerHTML=`SCORE: <b style="color:#65e7fa">${this.score}</b><br>HIGH: ${this.high}<br>HEAT: ${this.level+1}<br>TIME: ${Math.ceil(this.time)}<br><small style="color:${this.status.startsWith('PERFECT')?'#74ffa3':this.status.startsWith('MISS')?'#ff8b78':'#d9c998'}">${this.status}</small>`;}
 render(ctx,view,camera,time){if(!this.active)return;ctx.save();camera.apply(ctx,view);const p=this.player;if(!this.ball)this._ball(ctx,p.x+15,p.y-22,7);else{const b=this.ball;ctx.fillStyle='rgba(0,0,0,.2)';ctx.beginPath();ctx.ellipse(b.x,b.y,9,4,0,0,Math.PI*2);ctx.fill();this._ball(ctx,b.x,b.y-b.z,8);}for(const q of this.fx){ctx.globalAlpha=Math.max(0,q.life/.72);ctx.fillStyle=q.c;ctx.fillRect(q.x-3,q.y-3,6,6);}ctx.globalAlpha=1;if(this.status.startsWith('PERFECT')){ctx.fillStyle='#fff4af';ctx.font='900 25px Trebuchet MS';ctx.textAlign='center';ctx.fillText('PERFECT! +1',HOOP.x,HOOP.y-82-Math.sin(time*8)*3);}ctx.restore();}
 _ball(ctx,x,y,r){ctx.fillStyle='#e87527';ctx.strokeStyle='#4c2515';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(x-r,y);ctx.lineTo(x+r,y);ctx.moveTo(x,y-r);ctx.quadraticCurveTo(x-r*.7,y,x,y+r);ctx.moveTo(x,y-r);ctx.quadraticCurveTo(x+r*.7,y,x,y+r);ctx.stroke();}
}
