const $=(s)=>document.querySelector(s);let csrf='';
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value??'—';if(cls)e.className=cls;return e};
const when=(v)=>v?new Date(v).toLocaleString():'—';
const short=(v)=>v?`${v.slice(0,8)}…${v.slice(-6)}`:'—';
async function api(url,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(csrf)headers['X-CSRF-Token']=csrf;const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opts,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}
function showLogin(message=''){ $('#app').hidden=true;$('#login').hidden=false;$('#login-msg').textContent=message;csrf=''; }
function showApp(admin){$('#login').hidden=true;$('#app').hidden=false;$('#who').textContent=admin.username;}
const hashLink=(hash)=>{if(!hash)return text('span','—');const e=text('span',short(hash),'hash');e.title=hash;return e};
function stat(value,label){const e=document.createElement('div');e.className='stat';e.append(text('b',String(value??0)),text('span',label));return e;}
function renderStats(s){const el=$('#stats');el.replaceChildren(stat(s.users,'Users'),stat(s.active_users,'Active · 24h'),stat(s.arcade_sessions_24h,'Arcade · 24h'),stat(s.referrals_24h,'Referrals · 24h'),stat(s.verification_queue,'Verification queue'));}
function screenshot(record){const box=document.createElement('div');box.className='shot';if(record.has_screenshot){const url=`/api/admin/social-proof?id=${encodeURIComponent(record.id)}`,img=document.createElement('img');img.src=url;img.alt='Submitted social verification screenshot';img.loading='lazy';const a=text('a','Open screenshot');a.href=url;a.target='_blank';a.rel='noopener noreferrer';box.append(img,a);}else box.append(text('span','No screenshot','hash'));return box;}
function renderQueue(rows){const root=$('#queue');root.replaceChildren();const pending=rows.filter(x=>x.status==='pending').length;$('#queue-count').textContent=`${pending} PENDING`;if(!rows.length){root.append(text('div','No social verification submissions.','empty'));return;}for(const r of rows){const card=document.createElement('article');card.className='submission';const who=document.createElement('div');who.append(text('strong',`@${r.x_username} · Attempt ${r.attempt_number||1}`),text('small',r.wallet_address),text('small',when(r.submitted_at)));if(r.review_note)who.append(text('small',`Review note: ${r.review_note}`));const proof=screenshot(r);const actions=document.createElement('div');actions.className='actions';if(r.status==='pending'){const approve=text('button','APPROVE'),reject=text('button','REJECT','danger');approve.addEventListener('click',()=>review(r.id,'approved',approve,reject));reject.addEventListener('click',()=>review(r.id,'rejected',approve,reject));actions.append(approve,reject);}else actions.append(text('span',r.status,r.status+' status'));card.append(who,proof,actions);root.append(card);}}
function fillTable(id,rows,cells){const root=$(id);root.replaceChildren();if(!rows.length){const tr=document.createElement('tr'),td=text('td','No records.','empty');td.colSpan=cells.length;tr.append(td);root.append(tr);return;}for(const r of rows){const tr=document.createElement('tr');for(const fn of cells){const td=document.createElement('td'),v=fn(r);td.append(v instanceof Node?v:text('span',v));tr.append(td);}root.append(tr);}}
function withdrawalActions(r){const box=document.createElement('div');box.className='actions';if(r.status!=='pending'){box.append(text('span','FINAL','readonly pill'));return box;}const sent=text('button','SENT'),cancel=text('button','CANCEL','danger'),failed=text('button','FAIL','danger'),buttons=[sent,cancel,failed],lock=v=>buttons.forEach(b=>b.disabled=v);sent.addEventListener('click',async()=>{const ref=prompt('Required payment transaction hash/reference:','')??null;if(ref===null)return;if(!ref.trim())return $('#app-msg').textContent='Payment reference is required.';if(!confirm(`Confirm you already sent ${r.amount} zkLTC to ${r.wallet}? This deducts the Arcade balance.`))return;lock(true);try{await api('/api/admin/withdrawals',{method:'POST',body:JSON.stringify({id:r.id,action:'sent',paymentReference:ref})});await load();}catch(e){$('#app-msg').textContent=e.message;lock(false);}});cancel.addEventListener('click',async()=>{const reason=prompt('Cancellation reason (optional):','');if(reason===null)return;lock(true);try{await api('/api/admin/withdrawals',{method:'POST',body:JSON.stringify({id:r.id,action:'cancelled',reason})});await load();}catch(e){$('#app-msg').textContent=e.message;lock(false);}});failed.addEventListener('click',async()=>{const reason=prompt('Failure reason (required):','');if(reason===null)return;if(!reason.trim())return $('#app-msg').textContent='Failure reason is required.';lock(true);try{await api('/api/admin/withdrawals',{method:'POST',body:JSON.stringify({id:r.id,action:'failed',reason})});await load();}catch(e){$('#app-msg').textContent=e.message;lock(false);}});box.append(sent,cancel,failed);return box;}
function render(d){
 renderStats(d.stats);renderQueue(d.verificationQueue);
 fillTable('#users',d.users,[r=>r.wallet_address,r=>when(r.created_at),r=>when(r.last_activity_at),r=>r.social_verified_at?text('span','VERIFIED','approved status'):text('span','NOT VERIFIED','pending status'),r=>r.referral_code||'—']);
 fillTable('#referrals',d.referrals,[r=>r.referrer_wallet,r=>r.referred_wallet,r=>r.referral_code,r=>text('span',r.qualification_status,r.qualification_status+' status'),r=>text('span',r.reward_status,r.reward_status+' status'),r=>when(r.created_at)]);
 fillTable('#games',d.gameActivity,[r=>r.game,r=>r.wallet_address,r=>`${r.score} / ${r.waves}`,r=>`${r.reward} zkLTC`,r=>text('span',r.validation_status,r.validation_status+' status'),r=>when(r.ended_at||r.started_at)]);
 fillTable('#withdrawals',d.withdrawals,[r=>{const x=document.createElement('div');x.append(text('span',short(r.id),'hash'),document.createElement('br'),text('small',short(r.user_wallet)));return x},r=>`${r.amount} zkLTC`,r=>r.wallet,r=>r.payment_reference||r.transaction_hash||'—',r=>text('span',r.status,r.status+' status'),r=>`${when(r.requested_at)} / ${when(r.sent_at)}`,r=>withdrawalActions(r)]);
 fillTable('#casino',d.casinoTransactions,[r=>r.game,r=>`${r.wager} / ${r.payout??'—'} zkLTC`,r=>r.user_wallet,r=>{const x=document.createElement('div');x.append(hashLink(r.wager_tx_hash),document.createElement('br'),hashLink(r.payout_tx_hash));return x},r=>text('span',r.status,r.status+' status'),r=>when(r.created_at)]);
 fillTable('#claims',d.casinoClaims,[r=>short(r.casino_session_id),r=>r.player_wallet,r=>`${r.wager} / ${r.payout} zkLTC`,r=>hashLink(r.transaction_hash),r=>text('span',r.status,r.status+' status'),r=>when(r.claimed_at||r.submitted_at||r.created_at)]);
 fillTable('#blockchain',d.blockchainTransactions,[r=>r.type,r=>`${r.amount??'—'} zkLTC`,r=>r.user_wallet,r=>text('span',short(r.contract_address),'hash'),r=>hashLink(r.transaction_hash),r=>text('span',`${r.status} · ${r.confirmations} conf`,r.status+' status'),r=>when(r.confirmed_at||r.submitted_at)]);
 fillTable('#audits',d.auditLogs,[r=>r.action,r=>`${r.entity_type}${r.entity_id?' · '+r.entity_id:''}`,r=>r.wallet_address||'system',r=>{const v=JSON.stringify(r.metadata||{});const e=text('span',v.length>180?v.slice(0,177)+'…':v,'hash');e.title=v;return e},r=>when(r.created_at)]);
}
async function load(){try{$('#app-msg').textContent='Loading…';const d=await api('/api/admin/dashboard');render(d);$('#app-msg').textContent='';}catch(e){if(e.message==='UNAUTHORIZED')showLogin('Your secure session expired.');else $('#app-msg').textContent=e.message;}}
async function review(id,status,...buttons){let note='';if(status==='rejected'){const entered=prompt('Optional rejection reason:','');if(entered===null)return;note=entered;}if(!confirm(`${status==='approved'?'Approve':'Reject'} this one-time verification? This does not send any payment.`))return;buttons.forEach(b=>b.disabled=true);try{await api('/api/admin/review',{method:'POST',body:JSON.stringify({id,status,note})});await load();}catch(e){$('#app-msg').textContent=e.message;buttons.forEach(b=>b.disabled=false);}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');btn.disabled=true;$('#login-msg').textContent='Signing in…';try{const d=await api('/api/admin/auth',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});csrf=d.csrf;$('#password').value='';showApp(d.admin);await load();}catch(e){showLogin(e.message==='TOO_MANY_ATTEMPTS'?'Too many attempts. Wait 15 minutes.':'Sign-in failed.');}finally{btn.disabled=false;}});
$('#refresh').addEventListener('click',load);$('#logout').addEventListener('click',async()=>{try{await api('/api/admin/auth',{method:'DELETE'});}catch{}showLogin('Signed out.');});
(async()=>{try{const d=await api('/api/admin/auth');csrf=d.csrf;showApp(d.admin);await load();}catch{showLogin();}})();
